# Generated by Django 3.1.4 on 2021-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_auto_20210119_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('bloodgroup', models.CharField(choices=[('bloodgroup', 'AB positive'), ('bloodgroup', 'AB negetive'), ('bloodgroup', 'A positive'), ('bloodgroup', 'A negetive'), ('bloodgroup', 'B positive'), ('bloodgroup', 'B negetive'), ('bloodgroup', 'O positive'), ('bloodgroup', 'O negetive')], max_length=70)),
            ],
        ),
    ]
