# Generated by Django 3.1.4 on 2021-01-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_auto_20210121_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
